namespace Heroes.ReplayParser.MPQFiles.DataStructures
{
    public enum GameEventType
    {
        CStartGameEvent = 2,
        CDropOurselvesEvent = 3,
        CUserFinishedLoadingSyncEvent = 5,
        CUserOptionsEvent = 7,
        CBankFileEvent = 9,
        CBankSectionEvent = 10,
        CBankKeyEvent = 11,
        CBankSignatureEvent = 13,
        CCameraSaveEvent = 14,
        CCommandManagerResetEvent = 25,
        CGameCheatEvent = 26,
        CCmdEvent = 27,
        CSelectionDeltaEvent = 28,
        CControlGroupUpdateEvent = 29,
        CSelectionSyncCheckEvent = 30,
        CResourceTradeEvent = 31,
        CTriggerChatMessageEvent = 32,
        CDynamicButtonSwapEvent = 33,
        CSetAbsoluteGameSpeedEvent = 34,
        CTriggerPingEvent = 36,
        CUnitClickEvent = 39,
        CTriggerSkippedEvent = 44,
        CTriggerSoundLengthQueryEvent = 45,
        CTriggerSoundOffsetEvent = 46,
        CTriggerTransmissionOffsetEvent = 47,
        CTriggerTransmissionCompleteEvent = 48,
        CCameraUpdateEvent = 49,
        CTriggerPlanetMissionLaunchedEvent = 53,
        CTriggerDialogControlEvent = 55,
        CTriggerSoundLengthSyncEvent = 56,
        CTriggerConversationSkippedEvent = 57,
        CTriggerMouseClickedEvent = 58,
        CTriggerMouseMovedEvent = 59,
        CTriggerHotkeyPressedEvent = 61,
        CTriggerTargetModeUpdateEvent = 62,
        CTriggerSoundtrackDoneEvent = 64,
        CTriggerKeyPressedEvent = 66,
        CTriggerCutsceneBookmarkFiredEvent = 97,
        CTriggerCutsceneEndSceneFiredEvent = 98,
        CGameUserLeaveEvent = 101,
        CGameUserJoinEvent = 102,
        CCommandManagerStateEvent = 103,
        CCmdUpdateTargetPointEvent = 104,
        CCmdUpdateTargetUnitEvent = 105,
        CHeroTalentSelectedEvent = 110,
        CHeroTalentTreeSelectionPanelToggled = 112
    }
}
